In [1]:
import numpy as np

<h2>For 2 x 2 Metrix :</h2>

In [22]:
df = np.array([[5, 4],
              [2,  3]])

In [11]:
# Finding the eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(df)

In [12]:
print("Eigenvalues:")
print(eigenvalues)

Eigenvalues:
[7. 1.]


In [13]:
print("Eigenvectors:")
print(eigenvectors)

Eigenvectors:
[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


<h2>For 3 x 3 Metrix :</h2>

In [18]:

df = np.array([[3, -4, 5],
              [1, 2, 3],
              [9, 8, 7]])

In [19]:
# Finding the eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(df)

In [20]:
print("Eigenvalues:")
print(eigenvalues)

Eigenvalues:
[12.89897949  3.10102051 -4.        ]


In [21]:
print("Eigenvectors:")
print(eigenvectors)

Eigenvectors:
[[-0.34101066 -0.69549388 -0.65306893]
 [-0.27843404  0.56786837 -0.24878817]
 [-0.89787873  0.44024287  0.71526598]]
